ALTER SEQUENCE cliente_id_seq RESTART WITH 1;
ALTER SEQUENCE fornecedor_id_seq RESTART WITH 1;
ALTER SEQUENCE funcionario_id_seq RESTART WITH 1;
ALTER SEQUENCE pedido_id_seq RESTART WITH 1;
ALTER SEQUENCE produto_id_seq RESTART WITH 1;
ALTER SEQUENCE usuario_id_seq RESTART WITH 1;